#!/usr/bin/env node
// Brings GLORB into this repo, whole.
//
// The portfolio's particles have to BE his particles -- the intro, the hero,
// every section's shape and the moves between them are one field, not a fake
// hand-off between two -- so his engine runs in this page rather than in an
// iframe. It is ported by COPYING, not by rewriting: every tuned number and
// every hard-won fix in glorp/index.html comes across byte for byte, and only
// what it touches outside itself is redirected, from the outside, by
// shadowing the names inside one wrapper function:
//
//   document   getElementById hands back the hero's own canvas for "c" and "gl"
//              and a detached stand-in for each of his HUD elements; body and
//              documentElement are the host box, so his theme classes land there
//   window     innerWidth/innerHeight are the HOST's size, and "resize" follows
//              the host; THREE and GLTFLoader come from this repo's vendor copy
//   location   reads as ?embed (plus theme and bg), under /glorp/, so his embed
//              mode -- the ghost room, the palette hook -- switches itself on
//   parent / addEventListener("message")
//              his embed protocol, rewired to a direct call: api.post(msg)
//   fetch      relative paths resolve against his repo, where his files live
//
// Re-run after he retunes Glorb:   npm run glorb   (reads ../glorp/index.html)
// The output, site/glorb/engine.js, is GENERATED. Do not edit it.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { execSync } from 'node:child_process';

const SRC = process.argv[2] || new URL('../../glorp/index.html', import.meta.url).pathname;
const OUT = new URL('../site/glorb/engine.js', import.meta.url).pathname;
const html = readFileSync(SRC, 'utf8');

// his engine is the one classic script that starts with "use strict"
const m = html.match(/<script>\s*\n"use strict";\n([\s\S]*?)\n<\/script>\s*\n<\/body>/);
if (!m) { console.error('could not find the engine script in', SRC); process.exit(1); }
let body = m[1];

let sha = '?';
try { sha = execSync('git rev-parse --short HEAD', { cwd: new URL('.', 'file://' + SRC).pathname }).toString().trim(); } catch {}

// THE FLOOR. The page's strip is a flat wall under him: a particle that goes
// below it is put back on it and loses its downward speed, so he squashes
// against the line. And his resting centre can be moved (the strip pushes the
// whole of him up the screen as it rises). Both are injected just after his own
// containment wall, which is the last thing each particle meets in a step.
const wallEnd = "          if (vn > 0) { vx[i] -= wnx * vn; vy[i] -= wny * vn; }\n        }\n      }\n";
if (!body.includes(wallEnd)) { console.error('containment wall not found -- has the physics loop changed?'); process.exit(1); }
body = body.replace(wallEnd, wallEnd + `      // the page's strip: a flat floor he cannot go through (see tools/port-glorb.mjs)
      if (py[i] > __floor) {
        py[i] = __floor - Math.random() * 2;
        if (vy[i] > 0) vy[i] *= -0.18;
        vx[i] *= 0.9;
      }
`);
const loopHead = "function loop() {\n";
if (!body.includes(loopHead)) { console.error('loop() not found'); process.exit(1); }
body = body.replace(loopHead, loopHead + "  if (__cy != null) cy = __cy;\n");

// The boot tail starts the loop at once; the port starts it when asked, so the
// page decides when the field exists (and a hidden hero costs nothing).
const tail = /\nbuildLut\(0\);\nloop\(\);\s*$/;
if (!tail.test(body)) { console.error('boot tail not found -- has the end of the script changed?'); process.exit(1); }
body = body.replace(tail, '\nbuildLut(0);\n__start = loop;\n');

const out = `// GENERATED by tools/port-glorb.mjs from glorp/index.html @ ${sha}. DO NOT EDIT.
// This is Glorb's own engine, byte for byte, inside one function whose
// document, window, location, fetch and message plumbing are redirected to
// the host element. See the tool for why and how.
import * as __THREE from '../../vendor/three.module.min.js';
import { GLTFLoader as __GLTFLoader } from '../../vendor/GLTFLoader.js';

export function createGlorb({ host, theme: __theme = 'dark', bg: __bg = '', base: __base = '/glorp/', onEvent = () => {} }) {
  const __real = globalThis;
  const canvas__ = host.querySelector('canvas.glorb-c') || host.appendChild(Object.assign(__real.document.createElement('canvas'), { className: 'glorb-c' }));
  const gl__ = host.querySelector('canvas.glorb-gl') || host.appendChild(Object.assign(__real.document.createElement('canvas'), { className: 'glorb-gl' }));
  const __stand = new Map();
  const __byId = (id) => id === 'c' ? canvas__ : id === 'gl' ? gl__
    : (__stand.get(id) || (__stand.set(id, __real.document.createElement(id === 'mic' || /Btn$/.test(id) ? 'button' : 'div')), __stand.get(id)));
  const __bind = (t, k) => { const v = t[k]; return typeof v === 'function' ? v.bind(t) : v; };
  const document = new Proxy(__real.document, { get(t, k) {
    if (k === 'getElementById') return __byId;
    if (k === 'body' || k === 'documentElement') return host;
    return __bind(t, k);
  } });
  const __resize = new Set();
  new ResizeObserver(() => __resize.forEach((f) => f())).observe(host);
  const window = new Proxy(__real, { get(t, k) {
    if (k === 'innerWidth') return host.clientWidth || 1;
    if (k === 'innerHeight') return host.clientHeight || 1;
    if (k === 'THREE') return __THREE;
    if (k === 'GLTFLoader') return __GLTFLoader;
    if (k === 'addEventListener') return (ev, f, o) => ev === 'resize' ? __resize.add(f) : t.addEventListener(ev, f, o);
    return __bind(t, k);
  } });
  const location = { search: '?embed&theme=' + __theme + (__bg ? '&bg=' + String(__bg).replace('#', '') : ''),
    hostname: 'colinwillow.github.io', pathname: '/glorp/', origin: __real.location.origin,
    set href(v) {}, get href() { return __real.location.href; } };
  const __bus = [];
  const addEventListener = (ev, f, o) => ev === 'message' ? __bus.push(f)
    : ev === 'resize' ? __resize.add(f) : __real.addEventListener(ev, f, o);
  const parent = { postMessage: (m) => { try { onEvent(m); } catch (e) {} } };
  const fetch = (u, o) => __real.fetch(typeof u === 'string' && !/^([a-z]+:|\\/)/i.test(u) ? __base + u : u, o);
  // paused, every frame he asks for is parked and handed back on resume, so a
  // hidden hero costs nothing and picks up exactly where it stopped
  let __paused = false; const __parked = new Set();
  const requestAnimationFrame = (f) => __paused ? (__parked.add(f), 0) : __real.requestAnimationFrame(f);
  let __start = null, __floor = 1e9, __cy = null;

${body}

  // ---- the handle the page drives him through ----
  if (__start) __start();
  return {
    canvas: canvas__,
    /** his embed protocol, delivered straight in: text, points, palette, theme, audio, level */
    post(msg) { for (const f of __bus) f({ data: msg, source: null }); },
    setFormation, goHome, cfg, drive,
    get n() { return Math.min(MAX, Math.round(cfg.count)); },
    // the particles themselves, for anything that needs to hand them over or take them back
    field: { px, py, vx, vy, pz, bx, by, formX, formY, formZ, formOn, pr },
    /** which particles are his core: pr[i] < core */
    get core() { return cfg.core; },
    get centre() { return { x: cx, y: cy, scale }; },
    /** formation targets are in these units: screen = centre + form * scale * formS */
    get formS() { return formS; },
    pause(p) {
      if (p === __paused) return; __paused = !!p;
      if (!__paused) { const fs = [...__parked]; __parked.clear(); lastT = performance.now(); fs.forEach((f) => __real.requestAnimationFrame(f)); }
    },
    resize() { __resize.forEach((f) => f()); },
    /** the strip's top edge in his canvas pixels (1e9 = no floor), and where his centre rests (null = middle) */
    setFloor(y) { __floor = y; },
    setCentreY(y) { __cy = y; },
  };
}
`;
mkdirSync(new URL('../site/glorb/', import.meta.url).pathname, { recursive: true });
writeFileSync(OUT, out);
console.log(`site/glorb/engine.js  ${(out.length / 1024).toFixed(0)} KB  from glorp @ ${sha}`);
